from setuptools import setup, find_packages

setup(
    name="x8dsub-byte",
    version="1.0.0",
    author="Mohamed Harris",
    author_email="getwinharris@gmail.com",
    description="x8Dsub-byte: Sub-byte Tensor Compression Library using b' = b * 0.001 algorithm",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/bapXai/x8Dsub-byte",
    packages=find_packages(where="bindings/python"),
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords=["x8dsub-byte", "bapx", "Tensors", "Pytorch", "Tensorflow", "sub-byte", "compression", "AI", "ML", "Mohamed Harris", "BapX Media Hub"],
    install_requires=[
        "torch>=1.7.0",
        "numpy>=1.19.0",
    ],
    python_requires=">=3.8",
    license="Apache-2.0",
    project_urls={
        "Homepage": "https://bapx.in",
        "Repository": "https://github.com/bapXai/x8Dsub-byte.git",
        "Documentation": "https://bapx.in/docs/x8dsub-byte",
        "Bug Reports": "https://github.com/bapXai/x8Dsub-byte/issues",
        "Twitter": "https://twitter.com/bapxai",
        "Facebook": "https://facebook.com/bapxmediahub",
        "Instagram": "https://www.instagram.com/bapxmediahub",
        "YouTube": "https://www.youtube.com/@bapxmediahub",
    },
)